require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

# $FirebaseSDKVersion = '7.11.0'
$FirebaseSDKVersion = '8.7.0'



target 'Messenger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'  
  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'
  # pod 'mobile-ffmpeg-full', '~> 4.2.LTS'
  # pod 'react-native-ffmpeg/https-lts', :path => '../node_modules/react-native-ffmpeg'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  use_native_modules!
  use_unimodules!
end
